targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
          include_if_null: false
          checked: false
          create_field_map: false
      drift_dev:
        options:
          store_date_time_values_as_text: true