import {
  IconAdjustments,
  IconAlertTriangle,
  IconAlignJustified,
  IconArchive,
  IconArrowLeft,
  IconArrowRight,
  IconBallpen,
  IconBell,
  IconBook2,
  IconBuildingArch,
  IconCalendarTime,
  IconCheck,
  IconChecks,
  IconChevronRight,
  IconCircle,
  IconCircleCheck,
  IconCircleMinus,
  IconCircleOff,
  IconCirclePlus,
  IconCircleX,
  IconClock,
  IconDownload,
  IconFileCode,
  IconFileText,
  IconFileUnknown,
  IconFiles,
  IconFolder,
  IconFolders,
  IconGridDots,
  IconGridPattern,
  IconHeadphones,
  IconHelp,
  IconInfoCircle,
  IconLayoutDashboard,
  IconList,
  IconLock,
  IconLogout,
  IconMail,
  IconMap2,
  IconMapPin,
  IconMenu2,
  IconMessage,
  IconMessageDots,
  IconMoonStars,
  IconMovie,
  IconNorthStar,
  IconPhoto,
  IconPlus,
  IconPresentation,
  IconSchool,
  IconSearch,
  IconSearchOff,
  IconSettings,
  IconSun,
  IconTable,
  IconTestPipe,
  IconTicket,
  IconTrash,
  IconUser,
  IconUserCircle,
  IconWriting,
  IconX,
  TablerIcon,
} from '@tabler/icons';

const webIcons: {[key: string]: TablerIcon} = {
  adjustments: IconAdjustments,
  'alert-triangle': IconAlertTriangle,
  'align-justified': IconAlignJustified,
  archive: IconArchive,
  'arrow-left': IconArrowLeft,
  'arrow-right': IconArrowRight,
  ballpen: IconBallpen,
  bell: IconBell,
  'book-2': IconBook2,
  'building-arch': IconBuildingArch,
  'calendar-time': IconCalendarTime,
  check: IconCheck,
  checks: IconChecks,
  'chevron-right': IconChevronRight,
  circle: IconCircle,
  'circle-check': IconCircleCheck,
  'circle-minus': IconCircleMinus,
  'circle-off': IconCircleOff,
  'circle-plus': IconCirclePlus,
  'circle-x': IconCircleX,
  clock: IconClock,
  download: IconDownload,
  'file-code': IconFileCode,
  'file-text': IconFileText,
  'file-unknown': IconFileUnknown,
  files: IconFiles,
  folder: IconFolder,
  folders: IconFolders,
  'grid-dots': IconGridDots,
  'grid-pattern': IconGridPattern,
  headphones: IconHeadphones,
  help: IconHelp,
  'info-circle': IconInfoCircle,
  'layout-dashboard': IconLayoutDashboard,
  list: IconList,
  lock: IconLock,
  logout: IconLogout,
  mail: IconMail,
  'map-2': IconMap2,
  'map-pin': IconMapPin,
  'menu-2': IconMenu2,
  message: IconMessage,
  'message-dots': IconMessageDots,
  'moon-stars': IconMoonStars,
  movie: IconMovie,
  'north-star': IconNorthStar,
  photo: IconPhoto,
  plus: IconPlus,
  presentation: IconPresentation,
  school: IconSchool,
  search: IconSearch,
  'search-off': IconSearchOff,
  settings: IconSettings,
  sun: IconSun,
  table: IconTable,
  'test-pipe': IconTestPipe,
  ticket: IconTicket,
  trash: IconTrash,
  user: IconUser,
  'user-circle': IconUserCircle,
  writing: IconWriting,
  x: IconX,
};

export default webIcons;
