name: react-native-android-build-apk
on:
  push:
    branches:
      - master
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install npm dependencies
        run: |
          npm install
      - name: Run Jest
        run: npm test
      - name: Link assets
        run: npx react-native link
      - name: Cache Gradle Wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-
      - name: Get keystore file
        run: echo ${{ secrets.DEV_KEYSTORE }} | base64 -d > $GITHUB_WORKSPACE/dev-key-store.jks
      - name: Build dev release variant
        env:
          ENVFILE: .env.dev
        run: cd android/ && ./gradlew assembleDevFlavorRelease --no-daemon
          -Pandroid.injected.signing.store.file=$GITHUB_WORKSPACE/dev-key-store.jks
          -Pandroid.injected.signing.store.password="${{ secrets.DEV_KEYSTORE_PASSWD }}"
          -Pandroid.injected.signing.key.alias="${{ secrets.DEV_KEYSTORE_ALIAS }}"
          -Pandroid.injected.signing.key.password="${{ secrets.DEV_KEY_PASSWD }}"
      - name: Delete keystore file
        if: always()
        run: shred -vz $GITHUB_WORKSPACE/dev-key-store.jks ; rm -f $GITHUB_WORKSPACE/dev-key-store.jks
      - name: Upload ARM64 binary
        uses: actions/upload-artifact@v1
        with:
          name: arm64
          path: android/app/build/outputs/apk/devFlavor/release/app-devFlavor-arm64-v8a-release.apk
      - name: Upload ARMEABI binary
        uses: actions/upload-artifact@v1
        with:
          name: armeabi-v7a
          path: android/app/build/outputs/apk/devFlavor/release/app-devFlavor-armeabi-v7a-release.apk
      - name: Upload universal binary
        uses: actions/upload-artifact@v1
        with:
          name: universal
          path: android/app/build/outputs/apk/devFlavor/release/app-devFlavor-universal-release.apk
