name: tests
on:
  workflow_call:
  workflow_dispatch:
jobs:
  run-tests:
    name: 'Run tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install npm dependencies
        run: yarn
      - name: Run Jest
        run: yarn run test
